### ISSUE TITLE
main.py line 99 could use a try catch

### ISSUE THREAD

**Issue by otagtekintorqata** [cosad3s/postleaks#2]
main.py line 99 could use a try catch. Just to catch blanks.

File "/home/ec2-user/.local/lib/python3.6/site-packages/postleaks/__main__.py", line 99, in display
    print("[" + d["key"] + "=" + repr(d["value"]) + "]", end='')
TypeError: must be str, not NoneType

**Comment by cosad3s** [comment]
Hi! If this is a bug, can you provide step to reproduce it (command line arguments for example) ?

**Comment by cosad3s** [comment]
Closed for inactivity. Feel free to reopen it with example please.

**Comment by fc-arvind** [comment]
![image](https://github.com/cosad3s/postleaks/assets/121044157/7d7d92f7-7877-4389-bcb8-f2a4336e99c0)
Command to reproduce: postleaks -k foursquare.com --extend-workspaces

**Comment by cosad3s** [comment]
Thanks for the suggestion @fc-arvind , do you have the last version of Postleaks (1.1.2) ? If not, can you retry after a little update ? On my side, I cannot reproduce the problem with version 1.1.2. Thanks!
