### ISSUE TITLE
Improve Error Handling in fail Function to Prevent Premature Exiting

### ISSUE THREAD

**Issue by fc-arvind** [cosad3s/postleaks#3]
**Problem**

Currently, the fail function in our codebase has a tendency to exit the code abruptly, hindering our ability to retrieve essential data that might still be available despite the encountered error. This behavior leads to incomplete data analysis and potentially overlooked insights.

**Proposed Solution**

To address this issue, we need to refactor the fail function to handle errors gracefully without exiting the code immediately. Instead, it should log the error, allowing the execution to continue and giving us the opportunity to salvage any available data. We need not always continue the code. But sometimes we should. 

![image](https://github.com/cosad3s/postleaks/assets/121044157/b7ecf8bd-453c-4985-9349-e936709e3ce4)

This is after my changes 
![image](https://github.com/cosad3s/postleaks/assets/121044157/31ec8ade-6854-4e0f-a0d3-be8687389e1f)

**Comment by cosad3s** [comment]
Thanks @fc-arvind , I have merged your PR.

I am not 100% sure the error screenshot was linked to the fix, I have identified a rate-limiting from Postman on workspaces searches but anyway it is good idea to not exit during a loop.

I have identified another problem with Whispers. I opened an issue at https://github.com/adeptex/whispers/issues/127.

**Comment by fc-arvind** [comment]
Hi @cosad3s , I am sorry. I have been sick for the past few days. I will take a look into this.
