### ISSUE TITLE
Feature Request (multiple keywords at once)

### ISSUE THREAD

**Issue by reewardius** [cosad3s/postleaks#7]
Hi, cosad3s

Is there any possibility to implement the following function, namely to pass the list of keywords via -kf file, instead of searching one by one, as it is implemented now?

```
> cat keywords

google.com
tesla.com
apple.com
```

Thanks in advance!

**Comment by cosad3s** [comment]
Thanks @reewardius for your suggestion. I'll take a look for that in the next month I think.
